# Generated by Django 2.0 on 2019-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyconnect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
