# Generated by Django 2.0 on 2019-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyconnect', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='pic-folder/default.png', upload_to='pic-folder/'),
        ),
    ]
